name: Sushi Tetsu
favicon: null
layout_spectrum: 0.3507875371724367
typography_spectrum: 0.6085988450795412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.13867677771486342
  lightness: 0.2844295499380678
  saturation: 0.36826361366547644
  rhythmicContrast: 0.9882865222170949
purpose: []
